apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: demshin/nginx
        volumeMounts:
          - mountPath: /app
            name: app
        readinessProbe:
          httpGet:
            port: 8000
            path: /index.html
        livenessProbe:
                tcpSocket:
                  port: 8000
      initContainers:
        - name: init-app
          image: busybox:1.32.0
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
          volumeMounts:
            - mountPath: /app
              name: app
      volumes:
        - name: app
          emptyDir: {}
